version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: "cast(date_date AS timestamp)"
        freshness: 
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: orders identifier
            tests:
              - not_null
          - name: products_id
            description: products identifier
          - name: revenue
            description: total money generated
          - name: quantity
            description: number of sales
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: products identifier
            tests:
              - not_null
              - unique
          - name: purchase_price
            description: price when the product was purchased
      - name: ship
        identifier: raw_gz_ship
        description: Greenweez logistics info
        columns:
          - name: orders_id
            description: orders identifier
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: shipping fee
          - name: logcost
            description: cost of logistics
          - name: ship_cost
            description: shipping costs
models:
  - name: int_orders_margin
    description: tabla intermedia de orders
    columns:
      - name: orders_id
        description: orders identifier
        tests:
          - not_null
          - unique
      - name: date_date
        description: date of transaction
        tests:
          - not_null
      - name: revenue
        description: ganancias menos costos
        tests:
          - not_null
      - name: quantity
        description: cantidad de transacciones
        tests:
          - not_null
      - name: purchase_cost
        description: costo de compra
        tests:
          - not_null
      - name: margin
        description: margen de ganancias
        tests:
          - not_null
  - name: int_orders_operational
    description: join entre tabla intermedia de orders y ship raw
    columns:
      - name: orders_id
        description: orders identifier
        tests:
          - not_null
          - unique
      - name: date_date
        description: date
        tests:
          - not_null
      - name: operational_margin
        description: operational margin
        tests:
          - not_null
      - name: quantity
        description: cantidad
        tests:
          - not_null
      - name: purchase_cost
        description: costo de compra
        tests:
          - not_null
      - name: margin
        description: margen de ganancia
        tests:
          - not_null
      - name: revenue
        description: ganancias menos costos
        tests:
          - not_null
      - name: shipping_fee
        description: cuota de envio
        tests:
          - not_null
      - name: logcost
        description: costo de logistica
        tests:
          - not_null
  - name: int_sales_margin
    description: tabla intermedia de sales
    columns:
      - name: date_date
        description: fecha de trnasaccion
        tests:
          - not_null
      - name: orders_id
        description: identificador de ordenes
        tests:
          - not_null
      - name: products_id
        description: identificador de productos
        tests:
          - not_null
      - name: revenue
        description: revenue
        tests:
          - not_null
      - name: quantity
        description: cantidad
        tests:
          - not_null
      - name: purchase_price
        description: costo de compra
        tests:
          - not_null
      - name: purchase_cost
        description: margen
        tests:
          - not_null
     
    